### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Debug Failure.

### ISSUE THREAD

**Issue by nusability** [framer/component-importer#11]
When I run `component-importer init my-component-library --mode plain` I get the following output

`✅ Generating  /…/Framer Test/XD Test.framerfx/node_modules/importer.config.json
(node:30666) UnhandledPromiseRejectionWarning: Error: Debug Failure.
    at /Users/…/.config/yarn/global/node_modules/typescript/lib/typescript.js:17855:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (/Users/…/.config/yarn/global/node_modules/typescript/lib/typescript.js:17855:21)
    at Object.createCompilerDiagnostic (/Users/…/.config/yarn/global/node_modules/typescript/lib/typescript.js:17900:20)
    at tryReadFile (/Users/…/.config/yarn/global/node_modules/typescript/lib/typescript.js:27999:40)
    at Object.readConfigFile (/Users/…/.config/yarn/global/node_modules/typescript/lib/typescript.js:27964:32)
    at parseTsConfig (/Users/…/.config/yarn/global/node_modules/@framerjs/component-importer/build/analyze/typescript.js:57:45)
    at Object.createFramerXProgram (/Users/…/.config/yarn/global/node_modules/@framerjs/component-importer/build/analyze/typescript.js:69:21)
    at Object.compile (/Users/…/.config/yarn/global/node_modules/@framerjs/component-importer/build/compile.js:64:47)
    at async Object.generateComponents (/Users/…/.config/yarn/global/node_modules/@framerjs/component-importer/build/cli/commandGenerateComponents.js:53:22)
(node:30666) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30666) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Not sure where to go from here. Googling that error didn't really help. Any pointers?

**Comment by nusability** [comment]
Workaround: open the package.json within the framer file and bump the react version to something like ^16.9
