### ISSUE TITLE
Examples do not work

### ISSUE THREAD

**Issue by zxti** [framer/component-importer#7]
I just tried running this on the given example packages, but got crashes.

Here is my repo to repro the issue:

https://github.com/zxti/component-importer-sandbox

After cloning that repo and running yarn, I try running:

```
$ yarn component-importer init @blueprintjs/core
yarn run v1.22.4
$ /Users/zxti/proj/tmpsandbox/component-importer-sandbox/node_modules/.bin/component-importer init @blueprintjs/core
✅ Generating  /Users/zxti/proj/tmpsandbox/component-importer-sandbox/importer.config.json
(node:19550) UnhandledPromiseRejectionWarning: Error: Debug Failure.
    at /Users/zxti/proj/tmpsandbox/component-importer-sandbox/node_modules/typescript/lib/typescript.js:17852:89
    at String.replace (<anonymous>)
    at formatStringFromArgs (/Users/zxti/proj/tmpsandbox/component-importer-sandbox/node_modules/typescript/lib/typescript.js:17852:21)
    at Object.createCompilerDiagnostic (/Users/zxti/proj/tmpsandbox/component-importer-sandbox/node_modules/typescript/lib/typescript.js:17897:20)
    at tryReadFile (/Users/zxti/proj/tmpsandbox/component-importer-sandbox/node_modules/typescript/lib/typescript.js:27996:40)
    at Object.readConfigFile (/Users/zxti/proj/tmpsandbox/component-importer-sandbox/node_modules/typescript/lib/typescript.js:27961:32)
    at parseTsConfig (/Users/zxti/proj/tmpsandbox/component-importer-sandbox/node_modules/@framerjs/component-importer/build/analyze/typescript.js:57:45)
    at Object.createFramerXProgram (/Users/zxti/proj/tmpsandbox/component-importer-sandbox/node_modules/@framerjs/component-importer/build/analyze/typescript.js:69:21)
    at Object.compile (/Users/zxti/proj/tmpsandbox/component-importer-sandbox/node_modules/@framerjs/component-importer/build/compile.js:64:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19550) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejec ¹.g/COMMIT_EDITMSG                                                    buffers
tion id: 1)
(node:19550) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Similar thing (but with more errors/warnings) when trying office-ui-fabric-react. Thanks for any help!

**Comment by nusability** [comment]
I've got the same issue.

@zxti did you ever find a workaround for this?

**Comment by nusability** [comment]
Actually I did find a workaround; open the package.json within the framer file and bump the react version to something like ^16.9
